# Generated by Django 4.2.7 on 2023-12-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_recipe_carbohydrates_alter_recipe_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='backend.tool'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='backend.user'),
        ),
    ]
