# Generated by Django 4.2.7 on 2023-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_recipe_tools_alter_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('meat', 'Meat'), ('fruit', 'Fruit'), ('vegetables', 'Vegetables'), ('spices', 'Spices'), ('other', 'Other'), ('grains', 'Grains')], max_length=20),
        ),
    ]
