# Generated by Django 4.2.7 on 2023-12-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('meat', 'Meat'), ('grains', 'Grains'), ('vegetables', 'Vegetables'), ('fruit', 'Fruit'), ('spices', 'Spices'), ('other', 'Other')], max_length=20),
        ),
    ]
