# Generated by Django 4.2.7 on 2023-12-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_ingredient_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='useringredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='useringredient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_ingredients', to='backend.user'),
        ),
    ]
