# Generated by Django 4.2.7 on 2023-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_useringredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
