# Generated by Django 4.2.7 on 2023-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_useringredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='units',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L'), ('dcl', 'Dcl')], max_length=20, null=True),
        ),
    ]
