# Generated by Django 4.2.7 on 2023-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_useringredient_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
