# Generated by Django 4.2.7 on 2023-12-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_useringredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useringredient',
            old_name='name',
            new_name='IngredientName',
        ),
        migrations.RenameField(
            model_name='useringredient',
            old_name='quantity',
            new_name='ammount',
        ),
        migrations.RenameField(
            model_name='useringredient',
            old_name='units',
            new_name='unit',
        ),
    ]
