# Generated by Django 4.0 on 2023-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_name_useringredient_ingredientname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='backend.Tool'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tools',
            field=models.ManyToManyField(related_name='users', to='backend.Tool'),
        ),
    ]
