# Generated by Django 4.2.7 on 2023-12-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_recipe_tools_alter_user_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(blank=True, max_length=64, null=True)),
                ('recipeID', models.IntegerField(blank=True, null=True)),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('meat', 'Meat'), ('grains', 'Grains'), ('vegetables', 'Vegetables'), ('fruit', 'Fruit'), ('spices', 'Spices'), ('alcohol', 'Alcohol'), ('dairy', 'Dairy'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='units',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L'), ('dcl', 'Dcl'), ('ks', 'Ks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='unit',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L'), ('dcl', 'Dcl'), ('ks', 'Ks')], max_length=20, null=True),
        ),
    ]
