# Generated by Django 4.0 on 2023-12-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_recipe_tools_alter_user_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('meat', 'Meat'), ('grains', 'Grains'), ('vegetables', 'Vegetables'), ('fruit', 'Fruit'), ('spices', 'Spices'), ('alcohol', 'Alcohol'), ('dairy', 'Dairy'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='units',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L'), ('dcl', 'Dcl'), ('ks', 'Ks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='unit',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L'), ('dcl', 'Dcl'), ('ks', 'Ks')], max_length=20, null=True),
        ),
    ]
