# Generated by Django 4.2.7 on 2023-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_calendarrecipe_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarrecipe',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
