# Generated by Django 4.0 on 2023-12-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_ingredient_category_and_more'),
        ('backend', '0013_alter_calendarrecipe_date'),
    ]

    operations = [
    ]
